services:
  jenkins_ec2:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend

networks:
  frontend:
    external: true